name: shopping_cart
description: Shopping Cart application for displaying the cart contents and completing payment.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http:
  url_launcher:
  cupertino_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/product-icons/

  fonts:
    - family: RobotoSlab
      fonts:
        - asset: fonts/RobotoSlab/RobotoSlab-Regular.ttf
          weight: 400
        - asset: fonts/RobotoSlab/RobotoSlab-Medium.ttf
          weight: 500
        - asset: fonts/RobotoSlab/RobotoSlab-Bold.ttf
          weight: 700
        - asset: fonts/RobotoSlab/RobotoSlab-Black.ttf
          weight: 900
